# Embedding dimension and depth will be overwritten later
DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swin
  NAME: swin_tiny_c24_patch4_window8_256
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 32
    DEPTHS: [2]
    NUM_HEADS: [ 4, 8, 16, 32, 64 ]
    WINDOW_SIZE: 8